services:
  api-server:
    image: bryanhonof/iot-api-server-app
    ports:
      - "8080:8080"
    volumes:
      - db:/var/lib/iot-api-server
    networks:
      - backend
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - db:/var/lib/iot-api-server
    networks:
      - backend
volumes:
  grafana-storage: {}
  db: {}
networks:
  backend: