services:
  api-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - iot-db:/var/lib/iot-server
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - iot-db:/var/lib/iot-server
volumes:
  grafana-storage: {}
  iot-db: {}